apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: default
  labels:
    chart: "grafana"
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: grafana
  template:
    metadata:
      labels:
        bb: grafana
    spec:
      containers:

      - name: grafana
        image: "{{ .Values.imageRepository }}"

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: grafana
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    targetPort: http-grafana
    nodePort: 32395