apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkmon
  namespace: default
  labels:
    chart: "networkmon"
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: networkmon
  template:
    metadata:
      labels:
        bb: networkmon
    spec:
      containers:
        - name: networkmon
          image: "{{ .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}"
        
        - name: grafana
            image: grafana/grafana:7.5.2
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
                name: http-grafana
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /robots.txt
                port: 3000
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 2
            livenessProbe:
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
            resources:
              requests:
                cpu: 150m
                memory: 250Mi
            volumeMounts:
              - mountPath: /var/lib/grafana
                name: grafana-pv

        - name: prometheus
          image: "prom/prometheus"

      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: networkmon-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: networkmon
  ports:
  - port: 2112
    targetPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 32395
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: prometheus
  ports:
  - port: 9090
    targetPort: 9090