apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkmon
  namespace: default
  labels:
    chart: "networkmon"
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: networkmon
  template:
    metadata:
      labels:
        bb: networkmon
    spec:
      containers:
      - name: networkmon
        image: "{{ .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}"
      
      - name: grafana
        image: "grafana/grafana"

      - name: prometheus
        image: "prom/prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: networkmon-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: networkmon
  ports:
  - port: 2112
    targetPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 34395
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: prometheus
  ports:
  - port: 9090
    targetPort: 9090