apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkmon
  namespace: default
  labels:
    chart: "networkmon"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: networkmon
  template:
    metadata:
      labels:
        app: networkmon
    spec:
      containers:
      - name: networkmon
        image: "{{ .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: networkmon
  namespace: default
spec:
  type: NodePort
  selector:
    app: networkmon
  ports:
  - port: 2112
    targetPort: 2112
    nodePort: 30001