apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
  labels:
    chart: "prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: prometheus
  template:
    metadata:
      labels:
        bb: prometheus
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.imageRepository }}"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 32394